### ISSUE TITLE
Crashes unhelpfully when existing CHANGELOG is not in expected format

### ISSUE THREAD

**Issue by bethesque** [dcrec1/conventional-changelog-ruby#6]
Happy to write a PR for this. I suggest that when the last tag or release date cannot be determined from the existing file, the user is prompted to set an environment variable `CONVENTIONAL_CHANGELOG_LAST_RELEASE` that can be used to enable the first generated logs to be prepended. From then on, it will be able to find the previous release name from the previously generated content.

**Comment by dcrec1** [comment]
I agree with you Beth, please write the PR and I will happily merge it.
